### ISSUE TITLE
OPC Import Parameters

### ISSUE THREAD

**Issue by chris-traxler** [vrvis/PRo3D#148]
The following parameters should be defined before importing OPCs, i.e. in the scene file:

- [ ] Rendering priority
- [ ] Parameters for triangle filters (see issues #146, #130 and  #23)

If not defined in the scene file, user defined default values should be used.

[Taken from @gpaar's minutes from the meeting on Feb. 11th, 2022.]

**Comment by gpaar** [comment]
Redundant  to https://github.com/pro3d-space/PRo3D/issues/220
