### ISSUE TITLE
FShade.Imperative.FShadeOnlyInShaderCodeException when loading Gale Crater OPC

### ISSUE THREAD

**Issue by NoxMortem** [vrvis/PRo3D#172]
Branch: `develop`
Commit: `c7a23037878344754e744486bd3b39e77f7397e7`

Steps:
- build.sh
- Open PRo3D.sln in Visual Studio 2019
- Build
- Run
- Open Gale "Gale Crater\opc\MslGaleDem_01_03"

**Exception**
```
FShade.Imperative.FShadeOnlyInShaderCodeException
  HResult=0x80131500
  Message=Exception_WasThrown
  Source=PRo3D.Base
  StackTrace:
   at PRo3D.Base.Shader.DepthOffset.depthDiff() in E:\repositories\Pro3D\src\PRo3D.Base\Utilities.fs:line 209
```
in `Pro3D\src\PRo3D.Base\Utilities.fs` lines:202-200,
``` fsharp
        [<GLSLIntrinsic("gl_DepthRange.near")>]
        let depthNear()  : float = onlyInShaderCode ""

        [<GLSLIntrinsic("gl_DepthRange.far")>]
        let depthFar()  : float = onlyInShaderCode ""

        [<GLSLIntrinsic("(gl_DepthRange.far - gl_DepthRange.near)")>]
        let depthDiff()  : float = onlyInShaderCode ""
```

**Comment by haraldsteinlechner** [comment]
those exceptions are only "first chance" - and can be savely ignored. The FShade shader system depends on them and there is no way around it...
In visual studio, you can ignore those in the debug/exceptions dialog.
