### ISSUE TITLE
Surface Switching

### ISSUE THREAD

**Issue by chris-traxler** [vrvis/PRo3D#42]
Switch between two surfaces via keyboard shortcut. This is a simple way to visually compare two surfaces, for example two different reconstructions of the same area. It can be used for change detection.

- [ ] Preselect surfaces in a dedicated GUI component.
- [x] Mechanisms to alternately toggle their visibility with a keyboard shortcut.

[Requirement P3D-P002](https://docs.google.com/spreadsheets/d/1gbHoNQO-qs3tZPxgrVB1wvHKHSp9h1SJUbN4hz-MCX4/edit#gid=0&range=35:35)

**Comment by RebeccaNowak** [comment]
Solved using the selected surfaces in the Comparison App. Could be solved using additional GUI elements, but to minimse cluttering of the GUI solved using existing infrastructure.
